module.exports = {
    CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
    CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST',
    DELETE_NOTIFICATION_REQUEST: 'DELETE_NOTIFICATION_REQUEST',
}