const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "",
    basePath: "",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        },
        {
            "name": "Document",
            "description": "Endpoints"
        },
        {
            "name": "Admin",
            "description": "Endpoints"
        },
        {
            "name": "Notification",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    definitions: {
        Document: {
            title: "Policy",
            url: "/upload/file-sgehehrt.pdf"
        },
        User: {
            name: "admin",
            role: "9",
            password: "123456789",
            avatar: "efwe56ge5g4e5"
        },
        Confirm: {
            status: "Open",
            userId: {
                $ref: '#/definitions/User'
            },
            docId: {
                $ref: '#/definitions/Document'
            }
        }
    }
}

const outputFile = "./swagger_output.json"
const endpointFiles = ["./src/routes/index.js"]

swaggerAutogen(outputFile, endpointFiles, doc).then(() => {
    require('./index')           // Your project's root file
})